version: '3.8'

services:
  patch:
    image: patch
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 2080:2080
      - 2443:2443
    networks:
      - backend
      - access
    environment:
      GIN_MODE: debug
      ENVIRONMENT: development
      PATCH_REDIS_HOST: redis
      PATCH_REDIS_PORT: 6379
      PATCH_REDIS_DB: 0
      PATCH_REDIS_PASSWORD: 
      PATCH_REDIS_IDLE: 10
      PATCH_REDIS_MAXACTIVE: 10
      PATCH_REDIS_IDLETIMEOUT: 240
      PATCH_API_HOST: localhost
      PATCH_API_PORT: 2070
      PATCH_API_REDIS: true
      PATCH_API_REDISDB: 1
      PATCH_DB_HOST: database
      PATCH_DB_PORT: 5432
      PATCH_DB_USER: postgres
      PATCH_DB_PASS: postgres
      PATCH_DB_NAME: postgres
      PATCH_DB_SSLMODE: disable
    command: sleep infinity
    container_name: patch_dev
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - backend
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgs_data:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pgs_data:
    driver: local
    name: pgs_data
  redis_data:
    driver: local
    name: redis_data
networks:
  backend:
   internal: true
  access:

