version: '3.4'

services:
  patch:
    image: patch
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 2070:2070
    networks:
      - backend
      - access
    environment:
      PATCH_DB_HOST: database
      PATCH_DB_PORT: 5432
      PATCH_DB_USER: postgres
      PATCH_DB_PASSWORD: postgres
      PATCH_DB_NAME: postgres
      PATCH_REDIS_HOST: redis
      PATCH_REDIS_PORT: 6379
      PATCH_REDIS_PASSWORD: ""
    command: /bin/sh -c "while sleep 1000; do :; done"
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - backend
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgs_data:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pgs_data:
    driver: local
    name: pgs_data
  redis_data:
    driver: local
    name: redis_data
networks:
  backend:
   internal: true
  access:

